version: '2'

services:

  backup:
    image: pockost/borgbackup
    volumes:
      - ${borg_target}:${borg_target}
    environment:
      BORG_PASSPHRASE: ${borg_passphrase}
      BORG_TARGET: ${borg_target}
      BORG_SOURCES: ${borg_sources}
      LFTP_TARGET: ${lftp_target}
      CRON_DELAY: ${cron_schedule}
      TZ: ${timezone}
      SLACK_WEBHOOK_URL: ${slack_webhook_url}
      SLACK_ALERT_IDENTIFIER: ${slack_alert_identifier}
      SLACK_ALERT_LINK: ${slack_alert_link}