version: '2'

services:

  ##########
  # Backup #
  ##########
  backup:
    image: pockost/borgbackup
    environment:
      BORG_PASSPHRASE: ${borg_passphrase}
      BORG_TARGET: ${borg_target}
      BORG_SOURCES: ${borg_sources}
      LFTP_TARGET: ${lftp_target}
      CRON_DELAY: ${cron_schedule}
      TZ: ${timezone}
      SLACK_WEBHOOK_URL: ${slack_webhook_url}
      SLACK_ALERT_IDENTIFIER: ${slack_alert_identifier}
      SLACK_ALERT_LINK: ${slack_alert_link}
    stdin_open: true
    volumes:
      - ${borg_target}:${borg_target}
    tty: true
    labels:
      io.rancher.container.pull_image: always