version: '2'

catalog:

  name: "Borg"
  version: "standard"
  description: "Free BorgBackup (short: Borg) is a deduplicating backup program"
  minimum_rancher_version: 1.6.0
  questions:

    - variable: borg_passphrase
      description: "Borg passphrase used to encrypt backups, set on first run"
      label: "Borg passphrase"
      required: true
      type: "string"

    - variable: borg_target
      description: "Directory used to stock backups"
      label: "Borg target"
      required: true
      type: "string"

    - variable: borg_sources
      description: "Comma delimited list of the directories used to make backups. YOU MUST ADD YOUR VOLUMES BY YOURSELF"
      label: "Borg source(s)"
      required: true
      type: "string"

    - variable: lftp_target
      description: "Domain name used to synchronize backups over lftp. Exemple: `dedibackup-dc2.online.net`"
      label: "LFTP target"
      required: true
      type: "string"

    - variable: cron_schedule
      description: "The schedule with the default cron syntaxe"
      label: "CRON Schedule"
      required: true
      default: "0 5 * * *"
      type: "string"

    - variable: timezone
      description: "Timezone used to setup containers date"
      label: "Timezone"
      required: true
      type: "string"

    - variable: slack_webhook_url
      description: "This webhook will be call if an error occured"
      label: "Slack webhook"
      type: "string"

    - variable: slack_alert_identifier
      description: "This identifier will be used to customize error notification"
      label: "Slack identifier"
      type: "string"

    - variable: slack_alert_link
      description: "This link will be used to customize error notification"
      label: "Slack link"
      type: "string"

services:

  backup:
    retain_ip: true
    scale: 1
    start_on_create: true