version: '2'

services:

  gitlab:
    image: gitlab/gitlab-ce:${gitlab_version}
    volumes:
      - ${gitlab_data_volume}:/var/opt/gitlab
      - ${gitlab_log_volume}:/var/log/gitlab
      - ${gitlab_conf_volume}:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: ${gitlab_omnibus_config}
    ports:
      - ${gitlab_ssh_port}:22/tcp

  runner01:
    image: gitlab/gitlab-runner:${gitlab_runner_version}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${gitlab_runner01_volume}:/etc/gitlab-runner

  runner02:
    image: gitlab/gitlab-runner:${gitlab_runner_version}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${gitlab_runner02_volume}:/etc/gitlab-runner
