version: '2'

services:

  gitlab:
    image: gitlab/gitlab-ce:10.7.3-ce.0
    volumes:
      - gitlab_app_data:/var/opt/gitlab
      - gitlab_log_data:/var/log/gitlab
      - gitlab_conf:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: ${gitlab_omnibus_config}
    ports:
      - ${gitlab_ssh_port}:22/tcp

  runner01:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner01_data:/etc/gitlab-runner

  runner02:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner02_data:/etc/gitlab-runner

volumes:

  gitlab_app_data:
    driver: rancher-nfs

  gitlab_log_data:
    driver: rancher-nfs

  gitlab_conf:
    driver: rancher-nfs

  runner01_data:
    driver: rancher-nfs

  runner02_data:
    driver: rancher-nfs
