version: '2'

catalog:

  name: "GitLab"
  version: "standard"
  description: "Free GitHub alternative"
  uuid: gitlab-1
  minimum_rancher_version: 1.6.0
  questions:

    - variable: gitlab_version
      description: "Specify GitLab base image version. Will be pull from Docker Hub"
      label: "GitLab version"
      required: true
      type: "string"

    - variable: gitlab_ssh_port
      description: "SSH port to expose on host. Will be used to bind TCP"
      label: "SSH port"
      required: true
      type: "string"

    - variable: gitlab_data_volume
      description: "Specify path to store GitLab data"
      label: "GitLab data volume"
      required: true
      type: "string"

    - variable: gitlab_log_volume
      description: "Specify path to store GitLab logs"
      label: "GitLab log volume"
      required: true
      type: "string"

    - variable: gitlab_conf_volume
      description: "Specify path to store GitLab configurations"
      label: "GitLab conf volume"
      required: true
      type: "string"

    - variable: gitlab_omnibus_config
      description: "Omnibus config used to setup GitLab"
      label: "Omnibus config"
      default: "## General\n\
      external_url '<EXTERNAL_URL>'\n\
      registry_external_url '<REGISTRY_EXTERNAL_URL>'\n\
      \n## GitLab rails\n\
      gitlab_rails['gitlab_shell_ssh_port'] = <GITLAB_SSH_PORT>\n\
      gitlab_rails['smtp_enable'] = <SMTP_ENABLE>\n\
      gitlab_rails['smtp_address'] = <SMTP_SERVER_ADDRESS>\n\
      gitlab_rails['smtp_port'] = <SMTP_PORT>\n\
      gitlab_rails['smtp_user_name'] = <SMTP_USER_NAME>\n\
      gitlab_rails['smtp_password'] = <SMTP_PASSWORD>\n\
      gitlab_rails['smtp_domain'] = <SMTP_DOMAIN>\n\
      gitlab_rails['smtp_authentication'] = <SMTP_AUTHENTICATION>\n\
      gitlab_rails['smtp_enable_starttls_auto'] = <SMTP_ENABLE_STARTTLS_AUTO>\n\
      gitlab_rails['smtp_tls'] = <SMTP_TLS>\n\
      gitlab_rails['smtp_openssl_verify_mode'] = <SMTP_OPENSSL_VERIFY_MODE>\n\
      gitlab_rails['gitlab_email_from'] = <GITLAB_EMAIL_FROM>\n\
      gitlab_rails['gitlab_email_reply_to'] = <GITLAB_EMAIL_REPLY_TO>\n\
      \n# Nginx\n\
      nginx['listen_port'] = 80\n\
      nginx['listen_https'] = false\n\
      \n# Registry Nginx\n\
      registry_nginx['listen_port'] = 5000\n\
      registry_nginx['listen_https'] = false\n\
      registry_nginx['proxy_set_headers'] = {\n\
      \t'X-Forwarded-Proto' => 'https'\n\
      \t'X-Forwarded-Ssl' => 'on'\n\
      }\n\
      \n# Registry\n\
      registry['registry_http_addr'] = 'localhost:5001'"
      type: "multiline"

    - variable: gitlab_runner_version
      description: "Specify GitLab runners base image version. Will be pull from Docker Hub"
      label: "GitLab runners version"
      required: true
      type: "string"

    - variable: gitlab_runner01_volume
      description: "Specify path to store GitLab runner01 data"
      label: "GitLab runner01 volume"
      required: true
      type: "string"

    - variable: gitlab_runner02_volume
      description: "Specify path to store GitLab runner02 data"
      label: "GitLab runner02 volume"
      required: true
      type: "string"

services:

  gitlab:
    retain_ip: true
    scale: 1
    start_on_create: true

  runner01:
    retain_ip: true
    scale: 1
    start_on_create: true

  runner02:
    retain_ip: true
    scale: 1
    start_on_create: true