version: '2'

catalog:

  name: "GitLab"
  version: "10.7"
  description: "Free GitHub alternative"
  uuid: gitlab-1
  minimum_rancher_version: 1.6.0
  questions:

    - variable: gitlab_ssh_port
      description: "SSH port to expose on host. Will be used to bind TCP"
      label: "SSH Port"
      required: true
      default: "1433"
      type: "string"

services:

  runner01:
    scale: 1
