version: '2'

catalog:

  name: "GitLab"
  version: "10.7.3-ce.0"
  description: "Free GitHub alternative"
  uuid: gitlab-1
  minimum_rancher_version: 1.6.0
  questions:

    - variable: gitlab_ssh_port
      description: "SSH port to expose on host. Will be used to bind TCP"
      label: "SSH Port"
      required: true
      default: "1433"
      type: "string"

    - variable: gitlab_omnibus_config
      description: "Omnibus config used to setup GitLab"
      label: "Omnibus Config"
      default: "## General\n
        external_url 'http://git.local'\n
        registry_external_url 'http://registry.local'"
      type: "multiline"

services:

  runner01:
    scale: 1
