version: '2'

services:

  ###########
  # MongoDB #
  ###########
  mongodb:
    image: mongo:${mongo_version}
    environment:
      TZ: ${timezone}
    volumes:
      - mongodb_data:/data/db

  #################
  # Elasticsearch #
  #################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${elasticsearch_version}
    environment:
      http.host: 0.0.0.0
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      cluster.name: ${elasticsearch_cluster_name}
      TZ: ${timezone}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  ###########
  # Graylog #
  ###########
  graylog:
    image: graylog/graylog:${graylog_version}
    environment:
      GRAYLOG_PASSWORD_SECRET: ${graylog_password_secret}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${graylog_password_sha2}
      GRAYLOG_WEB_ENDPOINT_URI: ${graylog_web_endpoint_uri}
      GRAYLOG_ROOT_TIMEZONE: ${timezone}
      TZ: ${timezone}
      volumes:
        - graylog_journal:/usr/share/graylog/data/journal
    ports:
      - 127.0.0.1:12201:12201/udp

volumes:

  mongodb_data:
    driver: ${volume_driver}

  elasticsearch_data:
    driver: ${volume_driver}

  graylog_journal:
    driver: ${volume_driver}
