version: '2'

services:

  ###########
  # MongoDB #
  ###########
  mongodb:
    image: mongo:${mongodb_version}
    environment:
      TZ: ${timezone}
    stdin_open: true
    volumes:
      - ${mongodb_volume}:/data/db
    tty: true
    labels:
      io.rancher.container.pull_image: always

  #################
  # Elasticsearch #
  #################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${elasticsearch_version}
    environment:
      http.host: 0.0.0.0
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      cluster.name: ${elasticsearch_cluster_name}
      TZ: ${timezone}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ${elasticsearch_volume}:/usr/share/elasticsearch/data
    tty: true
    labels:
      io.rancher.container.pull_image: always

  ###########
  # Graylog #
  ###########
  graylog:
    image: graylog/graylog:${graylog_version}
    environment:
      GRAYLOG_PASSWORD_SECRET: ${graylog_password_secret}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${graylog_password_sha2}
      GRAYLOG_WEB_ENDPOINT_URI: ${graylog_web_endpoint_uri}
      GRAYLOG_ROOT_TIMEZONE: ${timezone}
      TZ: ${timezone}
    stdin_open: true
    network_mode: host
    volumes:
      - ${graylog_volume}:/usr/share/graylog/data/journal
    tty: true
    ports:
      - 12201:12201/udp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'