version: '2'

catalog:

  name: "Graylog"
  version: "standard"
  description: "Log management platform"
  minimum_rancher_version: 1.6.0
  questions:

    - variable: mongodb_version
      description: "Specify MongoDB base image version. Will be pull from Docker Hub"
      label: "MongoDB Version"
      required: true
      type: "string"

    - variable: mongodb_volume
      description: "Specify path to store MongoDB data"
      label: "MongoDB Volume"
      required: true
      type: "string"

    - variable: elasticsearch_version
      description: "Specify Elasticsearch base image version. Will be pull from Docker Hub"
      label: "Elasticsearch Version"
      required: true
      type: "string"

    - variable: elasticsearch_volume
      description: "Specify path to store Elasticsearch data"
      label: "Elasticsearch Volume"
      required: true
      type: "string"

    - variable: elasticsearch_cluster_name
      description: "Elasticsearch cluster name"
      label: "Elasticsearch Cluster Name"
      required: true
      type: "string"

    - variable: graylog_version
      description: "Specify Graylog base image version. Will be pull from Docker Hub"
      label: "Graylog Version"
      required: true
      type: "string"

    - variable: graylog_volume
      description: "Specify path to store Graylog data"
      label: "Graylog Volume"
      required: true
      type: "string"

    - variable: graylog_password_secret
      description: "Graylog secret password, Generate with: pwgen -N 1 -s 96"
      label: "Graylog Secret Password"
      required: true
      type: "string"

    - variable: graylog_password_sha2
      description: "Graylog root password sha2, Generate with: echo -n yourpassword | shasum -a 256"
      label: "Graylog Root Password Sha2"
      required: true
      type: "string"

    - variable: graylog_web_endpoint_uri
      description: "Graylog URL, used to generate assets url. Must end by slash"
      label: "Graylog URL"
      required: true
      type: "string"

    - variable: timezone
      description: "Timezone used to setup containers date"
      label: "Timezone"
      required: true
      type: "string"


services:

  mongo:
    retain_ip: true
    scale: 1
    start_on_create: true

  elasticsearch:
    retain_ip: true
    scale: 1
    start_on_create: true

  graylog:
    retain_ip: true
    scale: 1
    start_on_create: true