version: '2'

catalog:

  name: "Wordpress"
  version: "sftp"
  description: "Blog tool, publishing platform and CMS"
  uuid: wordpress-1
  minimum_rancher_version: 1.6.0
  questions:

    - variable: wordpress_version
      description: "Specify Wordpress base image version. Will be pull from Docker Hub"
      label: "Wordpress Version"
      required: true
      default: "latest"
      type: "string"

    - variable: mariadb_version
      description: "Specify MariaDB base image version. Will be pull from Docker Hub"
      label: "MariaDB Version"
      required: true
      default: "latest"
      type: "string"

    - variable: mariadb_database
      description: "MariaDB database name, create on first run"
      label: "MariaDB Database"
      required: true
      default: "super_database"
      type: "string"

    - variable: mariadb_root_password
      description: "MariaDB root password, set on first run. Default: super_password"
      label: "MariaDB Root Password"
      required: true
      default: "super_password"
      type: "password"

    - variable: mariadb_user
      description: "MariaDB user, set on first run"
      label: "MariaDB User"
      required: true
      default: "super_user"
      type: "string"

    - variable: mariadb_user_password
      description: "MariaDB user password, set on first run. Default: super_password"
      label: "MariaDB User Password"
      required: true
      default: "super_password"
      type: "password"

    - variable: sftp_version
      description: "Specify Atmoz/SFTP base image version. Will be pull from Docker Hub"
      label: "Atmoz/SFTP Version"
      required: true
      default: "latest"
      type: "string"

    - variable: sftp_port
      description: "SFTP port to expose on host"
      label: "SFTP Port"
      required: true
      type: "string"

    - variable: sftp_user
      description: "SFTP user used to connect"
      label: "SFTP User"
      required: true
      type: "string"

    - variable: sftp_password
      description: "SFTP password used to connect"
      label: "SFTP Password"
      required: true
      type: "password"

    - variable: timezone
      description: "Timezone used to setup containers date"
      label: "Timezone"
      required: true
      default: "Europe/Paris"
      type: "string"

    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "rancher-nfs"
      type: enum
      options:
        - local
        - rancher-nfs
