version: '2'

services:

  ############
  # InfluxDB #
  ############
  influxdb:
    image: influxdb:${influxdb_version}
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: true
      INFLUXDB_DB: ${influxdb_database}
      INFLUXDB_ADMIN_USER: ${influxdb_admin}
      INFLUXDB_ADMIN_PASSWORD: ${influxdb_admin_password}
      INFLUXDB_USER: ${influxdb_user}
      INFLUXDB_USER_PASSWORD: ${influxdb_user_password}
    stdin_open: true
    volumes:
      - ${influxdb_volume}:/var/lib/influxdb
    tty: true
    labels:
      io.rancher.container.pull_image: always

  ############
  # Telegraf #
  ############
  telegraf:
    image: pockost/telegraf-rancher
    environment:
      HOST_MOUNT_PREFIX: /hostfs
      INFLUXDB_HOST: http://influxdb:8086
      INFLUXDB_NAME: ${influxdb_database}
      INFLUXDB_USER: ${influxdb_user}
      INFLUXDB_PASSWORD: ${influxdb_user_password}
      MOUNT_POINTS: ${mount_points}
    stdin_open: true
    volumes:
    - /var/run/utmp:/var/run/utmp:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /:/hostfs:ro
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'

  ###########
  # Grafana #
  ###########
  grafana:
    image: grafana/grafana:${grafana_version}
    environment:
      GF_SERVER_ROOT_URL: ${grafana_url}
    stdin_open: true
    volumes:
      - ${grafana_volume}:/var/lib/grafana
    tty: true
    labels:
      io.rancher.container.pull_image: always
