version: '2'

catalog:

  name: "Grafana"
  version: "1.0.0"
  description: "Virtualization dashboard"
  uuid: grafana-1
  minimum_rancher_version: 1.6.0
  questions:

    - variable: grafana_version
      description: "Specify Grafana base image version. Will be pull from Docker Hub"
      label: "Grafana Version"
      required: true
      type: "string"

    - variable: grafana_url
      description: "Grafana URL, used to generate assets url"
      label: "Grafana URL"
      required: true
      type: "string"

    - variable: grafana_volume
      description: "Specify path to store Grafana data."
      label: "Grafana Volume"
      required: true
      type: "string"

    - variable: influxdb_database
      description: "InfluxDB database name, create on first run"
      label: "InfluxDB Database"
      required: true
      type: "string"

    - variable: influxdb_admin
      description: "InfluxDB admin, set on first run"
      label: "InfluxDB Admin"
      required: true
      type: "string"

    - variable: influxdb_admin_password
      description: "InfluxDB admin password, set on first run. Default: influx_admin_password"
      label: "InfluxDB Admin Password"
      required: true
      type: "password"

    - variable: influxdb_user
      description: "InfluxDB user, set on first run"
      label: "InfluxDB User"
      required: true
      type: "string"

    - variable: influxdb_user_password
      description: "InfluxDB user password, set on first run. Default: influxdb_user_password"
      label: "InfluxDB User Password"
      required: true
      type: "password"

    - variable: influxdb_volume
      description: "Specify path to store InfluxDB data."
      label: "InfluxDB Volume"
      required: true
      type: "string"

services:

  grafana:
    scale: 1

  influxdb:
    scale: 1
