version: '2'

catalog:

  name: "Grafana"
  version: "standard"
  description: "Virtualization dashboard"
  uuid: grafana-1
  minimum_rancher_version: 1.6.0
  questions:

    - variable: grafana_version
      description: "Specify Grafana base image version. Will be pull from Docker Hub"
      label: "Grafana Version"
      required: true
      type: "string"

    - variable: grafana_volume
      description: "Specify path to store Grafana data. Must be owned by 472:472"
      label: "Grafana Volume"
      required: true
      type: "string"

    - variable: grafana_url
      description: "Grafana URL, used to generate assets url. Must end by slash"
      label: "Grafana URL"
      required: true
      type: "string"

    - variable: influxdb_version
      description: "Specify InfluxDB base image version. Will be pull from Docker Hub"
      label: "InfluxDB Version"
      required: true
      type: "string"

    - variable: influxdb_volume
      description: "Specify path to store InfluxDB data"
      label: "InfluxDB Volume"
      required: true
      type: "string"

    - variable: influxdb_database
      description: "InfluxDB database name, create on first run"
      label: "InfluxDB Database"
      required: true
      type: "string"

    - variable: influxdb_admin
      description: "InfluxDB admin, set on first run"
      label: "InfluxDB Admin"
      required: true
      type: "string"

    - variable: influxdb_admin_password
      description: "InfluxDB admin password, set on first run"
      label: "InfluxDB Admin Password"
      required: true
      type: "password"

    - variable: influxdb_user
      description: "InfluxDB user, set on first run"
      label: "InfluxDB User"
      required: true
      type: "string"

    - variable: influxdb_user_password
      description: "InfluxDB user password, set on first run"
      label: "InfluxDB User Password"
      required: true
      type: "password"

services:

  influxdb:
    retain_ip: true
    scale: 1
    start_on_create: true

  telegraf:
    retain_ip: true
    start_on_create: true

  grafana:
    retain_ip: true
    scale: 1
    start_on_create: true