version: '2'

catalog:

  name: "Grafana"
  version: "5.0.2"
  description: "Virtualization dashboard"
  uuid: grafana-1
  minimum_rancher_version: 1.6.0

services:

  grafana:
    scale: 1

  influxdb:
    scale: 1
